include:
  - yaml/db.yml
  - yaml/auth.yml
  - yaml/chat.yml
  - yaml/frontend.yml
  - yaml/proxy.yml
  - yaml/prometheus.yml
  - yaml/grafana.yml

volumes:
  db-data:
  prometheus-data:
  grafana-data:
